-- Database Schema for Cariñosas.top
-- Create models table for VIP profiles

CREATE TYPE plan_type AS ENUM ('Bronce', 'Plata', 'Oro');

CREATE TABLE IF NOT EXISTS models (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  city TEXT NOT NULL, -- Quito, Guayaquil, Cuenca, Manta
  age INTEGER NOT NULL,
  whatsapp TEXT NOT NULL,
  description TEXT,
  plan_type plan_type DEFAULT 'Bronce' NOT NULL,
  is_verified BOOLEAN DEFAULT false NOT NULL,
  images TEXT[] DEFAULT '{}', -- Array of Uploadthing URLs
  tags TEXT[] DEFAULT '{}', -- Generated by Stitch
  is_online BOOLEAN DEFAULT false NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE models ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public profiles are viewable by everyone" 
  ON models FOR SELECT 
  USING (true);

CREATE POLICY "Models can update their own profile" 
  ON models FOR UPDATE 
  USING (true); -- In a production app, we would use auth.uid()
