-- Database Schema for Cariñosas.top
-- Create models table for VIP profiles

-- Drop old objects if updating
DROP TABLE IF EXISTS models;
DROP TYPE IF EXISTS plan_type;

-- Visibility plans matching the codebase
CREATE TYPE plan_type AS ENUM ('Anuncio Gratis', 'Premium', 'Diamante', 'VIP Elite');

CREATE TABLE IF NOT EXISTS models (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  name TEXT NOT NULL,
  city TEXT NOT NULL, -- Quito, Guayaquil, Cuenca, Manta, etc.
  sector TEXT, -- Sector/Reference description
  age INTEGER DEFAULT 21 NOT NULL,
  whatsapp TEXT NOT NULL,
  description TEXT,
  plan_type plan_type DEFAULT 'Anuncio Gratis' NOT NULL,
  is_verified BOOLEAN DEFAULT false NOT NULL,
  is_verified_4k BOOLEAN DEFAULT false NOT NULL,
  images TEXT[] DEFAULT '{}', -- Array of Uploadthing URLs
  tags TEXT[] DEFAULT '{}', -- Generated by Stitch
  is_online BOOLEAN DEFAULT false NOT NULL,
  is_boosted BOOLEAN DEFAULT false NOT NULL,
  personal_note TEXT DEFAULT 'Un encuentro inolvidable te espera...',
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION
);

-- Enable Row Level Security (RLS)
ALTER TABLE models ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Public profiles are viewable by everyone" 
  ON models FOR SELECT 
  USING (true);

-- WRITE OPERATIONS (INSERT, UPDATE, DELETE) ARE DISABLED FOR PUBLIC KEYS.
-- Writes are executed exclusively via server actions using the service_role key.
